--- 
- 
  name: "Get all state"
  set_fact: 
    all_state: "{{lookup('asb_state', get_all=True) }}"
- 
  debug: "msg=\"the value of somekey is {{all_state.somekey}}\""
- 
  name: "asb_state lookup single key"
  set_fact: 
    some_test_var: "{{lookup('asb_state', 'anotherkey') }}"
- 
  debug: "msg=\"the value of anotherkey is {{some_test_var}}\""
- 
  asb_set_state: 
    fields: 
      someotherkey: some_val
  name: "Add some more state"
- 
  asb_encode_binding: 
    fields: 
      CLIENT_ID: "default"
